### ISSUE TITLE
Major save issue

### ISSUE THREAD

**Issue by Xynocide** [Project-Junebug/Junebug-2#20]
Saving causes an error box, shown bellow, and results in the application closing and the save file being wiped.
![12919126_512308168970441_1544786015_n](https://cloud.githubusercontent.com/assets/17913094/14067965/69586716-f46c-11e5-9aee-52627811012c.jpg)

**Comment by Mutantoe** [comment]
That's a segfault.

**Comment by Mutantoe** [comment]
This is a different issue to #14. This can be fixed by adding a `PageType::Info` checkpoint on the page before.

**Comment by Mutantoe** [comment]
Fixed
