### ISSUE TITLE
"Open With" Junebug

### ISSUE THREAD

**Issue by Mutantoe** [Project-Junebug/Junebug-2#4]
Make Windows able to have Junebug selected as the default file handler for a save file to allow for simple file openings. Probably done through a command line argument.

**Comment by Mutantoe** [comment]
This may not be possible due to the fact that the program is going to be primarily distributed on disks.

**Comment by Xynocide** [comment]
An autorun script should be sufficient for on disks. And if memory stick users cannot figure out how to open the program then this challenge may not be for them.

**Comment by Mutantoe** [comment]
I think you have the wrong end of the stick (no pun intended). By "open with" I mean selecting the application as the default opener for the .sav files. So, when you double-click a .sav it will open with Junebug.

**Comment by Xynocide** [comment]
I see, I know this can be done, but I do not know of a way to make it automatic.

**Comment by Mutantoe** [comment]
It's probably done by taking the file path as a command line argument.

**Comment by Mutantoe** [comment]
So an argument in the constructor of `MainWindow` is probably needed, then `m_list.loadSaveData` can be called.

**Comment by Mutantoe** [comment]
Cannot implement in this release
